config/routes.rb
Rails.application.routes.draw do

  resources :customers, only: :show
  resources :supermarkets, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :supermarket
   has_many :customer_items
   has_many :items, through: :customer_items

   def total_cost
    items.sum(:price)
   end

end

app/models/customer_item.rb
class CustomerItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :customer_items
  has_many :customers, through: :customer_items
end

app/models/supermarket.rb
class Supermarket < ApplicationRecord
  has_many :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def show
      @customer = Customer.find(params[:id])
  end

end

app/controllers/supermarkets_controller.rb
class SupermarketsController < ApplicationController

  def index
    @supermarket = Supermarket.all

  end

  def show
      @supermarket = Supermarket.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/show.html.erb
<h1><%= @customer.supermarket.name %></h1>

<h2>Total Cost: <%= @customer.total_cost %></h2>

<% @customer.items.each do |items| %>
<h3><%= items.name %></h3>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>B2Assessments</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/supermarkets/index.html.erb
<h1>Supermarket Index Page</h1>

app/views/supermarkets/show.html.erb
<h1><%= @supermarket.name %></h1>

<p><%= link_to "Supermarket Index", supermarkets_path %> </p>